services:
  - type: web
    name: USD_rate_bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false          # задаёшь в панели Render
      - key: WEBHOOK_BASE_URL
        value: "https://cbr-course-bot.onrender.com"  # поменяй на свой URL
      - key: DATABASE_PATH
        value: "bot.db"